version: "3.7"

services:
  

  #Camunda Database
  mysql-db-camunda:
    container_name: mysql-db-camunda
    image: mysql:${MYSQL_VERSION}
    restart: always
    volumes:
      - ./db/mysql-db-camunda/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    healthcheck:    
      test: "exit 0"
    ports:
      - "3306:3306"  
    networks:
      - stack1-network
    
volumes:
  mysql-db-camunda:

networks:
  stack1-network:
    driver: bridge  
    
    
 